server:
  port: 8081
spring:
  application:
    name: mqtt-producer-server

logging:
  level:
    root: info
    com.samin.mqtt: debug

mqtt:
  url: ${MQTT_URL:tcp://samindev:1883}
  username: ${MQTT_USERNAME:samin}
  password: ${MQTT_PASSWORD:samin123}
  client-id-prefix: ${MQTT_CLIENT_ID_PREFIX:producer-}
  qos: ${MQTT_QOS:0}
  keep-alive: ${MQTT_KEEP_ALIVE:20}
  connection-timeout: ${MQTT_CONN_TIMEOUT:10}
  clean-session: ${MQTT_CLEAN_SESSION:true}
  pool-size: ${MQTT_POOL_SIZE:4}
  task:
    enabled: ${MQTT_TASK_ENABLED:true}
